camera_server:
  # Video feed options
  stream_type: "UDP" # Supports HTTP or UDP
  stream_port: 5600
  stream_address: '0.0.0.0' #real "127.0.0.1"

  # HTTP Broadcast options
  broadcast_port: 8080
  broadcast_address: "/"
  number_threads: 10
  image_quality: 30   # Ints from 0<->100 %